project:
  type: website

website:
  title: "Home"
  description: "This is Luis Montillas's academic website."
  navbar:
    right:
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: timeline.qmd
        text: Timeline
      - href: scicomm.qmd
        text: SciComm
format:
  html:
    theme: theme.scss
    css: styles.css



