project:
  type: website
  resources:
    "/.well-known/atproto-did"

website:
  title: "Home"
  description: "This is Luis Montillas's academic website."
  site-url: https://www.luismmontilla.com/
  cookie-consent: true
  navbar:
    right:
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: timeline.qmd
        text: Timeline
      - href: scicomm.qmd
        text: SciComm
format:
  html:
    theme:
      dark: darkly




